Feature/mypage
TeamHavit/Havit-Android pull request #352
Opened 2022-02-28 10:42 UTC by ny2060

- closed #351 
- closed #348 
- closed #344

2022-02-28 11:26 UTC, KxxHyoRim requested changes
확인했슴니다~~👍👍

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/res/layout/fragment_my_page.xml
> +
뷰를 위에서부터 본다고 가정 했을때, 상단에 위치한 TextView니까
전체 xml의 상단으로 이동하면 더 뷰를 파악하기 용이할것 같아요!😉

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/res/layout/fragment_my_page.xml
> +            android:id="@+id/tv_my_page_percent_mark"
또한 my_page이내의 뷰임은 xml의 이름을 통해서 파악 할 수 있기에
네이밍을 아래와 같이 간결하게 설정할 수도 있겠네요😎

```suggestion
            android:id="@+id/tv_rate"
```

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
>              btn.setBackgroundColor(Color.parseColor("#afafb7"))
해당 커밋과는 큰 관련이 없지만 colors.xml로 관리해주면 편리 할 듯 합니다~

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
> +    fun setDescription(textView: TextView, rate: Int?) {
rate 변수의 타입이 Int?인 이유가 무엇일까요..?
MyPageViewmodel.kt를 보면 도달률을 계산하는 두 int가 모두 Int? 타입이 아니기 때문에
null이 넘어올 상황은 없을 것 같은데 제가 잘못 이해한걸 까요..?!?

그리고 Int? 타입을 사용하실거라면, 아래 when 문에서 else를 활용하여
적절한 예외처리를 해주는게 좋을 것 같습니다!

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
> +            _rate.postValue((response.totalSeenContentNumber.toDouble() / response.totalContentNumber.toDouble() * 100).toInt())
https://toepic.fail/kotlin-division-by-zero-c019883cb089

0으로 나누는 상황이 발생할 수 있지 않을까 싶어서 kotlin에서 0으로 나누는 경우에 어떻게 되는지 검색해보았는데요!
Infinity의 결과가 도출 된다고 합니다~

초기 유저의 경우 totalSeenContents와 totalContentsNum 모두 0일 가능성이 있으니
0으로 나눌경우에 대한 예외처리 코드를 추가해주세요!

@yubinquitous 유빈님도 메인뷰에서 혹시 0에대한 예외처리가 되어 있는지 한 번 더 확인 부탁드립니다❤

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
> +            100 -> Glide.with(imageView).load(R.drawable.ic_illust_light_4).into(imageView)
도달률과 관련된 숫자(0,33,66...) 부분이 ImageView와 TextView를 처리할 때 모두 쓰이던데
companion object {} 내부에 private const val 변수를 선언해서 상수로 관리하면 더욱 편리하지 않을까요!?😎

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
> +    fun setDescriptionImg(imageView: ImageView,rate: Int?){
이부분도 마찬가지로 Int? 타입을 사용하군요👀

2022-02-28 11:26 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
> +            100 -> Glide.with(imageView).load(R.drawable.ic_illust_light_4).into(imageView)
또한 일러스트 이미지를 light1,2,... 보다는
ic_illust_stage_1 (?) 뭐 이런식으로 바꿔도 좋을것같네욤👻👻

2022-02-28 11:31 UTC, yubinquitous commented on app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
> +            _rate.postValue((response.totalSeenContentNumber.toDouble() / response.totalContentNumber.toDouble() * 100).toInt())
당신정말,, 최고네요,, 예외처리코드 추가하겠습니닷~~~!

2022-03-03 08:27 UTC, KxxHyoRim approved these changes
리팩토링 고생하셧슴니다아ㅏ..!
네이밍만 바꾸고 머지하면 될듯..!!

2022-03-03 08:27 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/ui/mypage/MyPageFragment.kt
> +    }
선생님 myPage라는 네이밍보다, clCategoryNum, clSavedContents, clSeenContents라고 네이밍 하면 코드가 더 직관적일 것 같습니다~

2022-03-03 08:27 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
> +            }
아주 좋아용~~👍👍

2022-03-03 08:27 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/ui/mypage/MyPagetoCategoryFragment.kt
> +class MyPagetoCategoryFragment : BaseBindingFragment<FragmentCategoryBinding>(R.layout.fragment_category) {
해당 Fragment가 MyPage에서 '카테고리 수'를 눌렀을 때 띄우는 뷰가 맞나요??ㅎㅎ
그렇다면 CategoryFromMyPageFragment 는 어떨가요..!?

2022-03-03 08:27 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/util/BindingAdapter.kt
> +            btn.setBackgroundColor(btn.context.getColor(R.color.gray_2))
감삼당~

2022-03-03 08:27 UTC, KxxHyoRim commented on app/src/main/res/navigation/nav_main.xml
> +        tools:layout="@layout/fragment_category"/>
tools에도 MyPagetoCategoryFragment를 넣어주시면 더 좋을것 같아요~~

2022-03-03 08:27 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/ui/mypage/MyPageViewModel.kt
> +            }
주석도 살포시 적으면 좋지않을까여~?? 0으로 나눌경우 어쩌구저쩌구..!📋📋

2022-03-08 08:47 UTC, merged