[REFACTOR] Savefragment 오타 수정 & 코드개선 (#364)
TeamHavit/Havit-Android pull request #365
Opened 2022-03-03 08:34 UTC by ny2060

- closed #364

2022-03-03 08:43 UTC, sdu07024 approved these changes
수고티비~!

2022-03-03 08:43 UTC, sdu07024 commented on app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
> +                    with(binding) {
반영 감사합니당><><

2022-03-03 08:52 UTC, KxxHyoRim requested changes
네이밍 바꿔주면 안잡아 먹..지..!🐯🐯

2022-03-03 08:52 UTC, KxxHyoRim commented on app/src/main/res/layout/fragment_save.xml
> +            android:id="@+id/cl_save_url_toast"
cl_paste_clip_board 로 바꿔달라고 하면 화낼거야 자기얌?❤

2022-03-03 08:52 UTC, KxxHyoRim commented on app/src/main/res/layout/fragment_save.xml
> +                android:id="@+id/tv_save_url_valid"
id 값 iv_unvalid_url, tv_unvalid_url 로 바꿔달라고 하면 혼나요?ㅋㅋㅋㅋㅋㅋㅋ

2022-03-03 08:52 UTC, KxxHyoRim commented on app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
> +                    this.getItemAt(0).text.toString().trim() // 클립보드에 저장된 첫번째 데이터
첫번째 데이터일것 같은건.. getItemAt(0) 만 봐도 알것같긴한데,,😂😂😂
클립보드에 있는 데이터 중에 젤 첫번째가 url이다 뭐 그런건가요.!??

2022-03-06 11:05 UTC, ny2060 commented on app/src/main/res/layout/fragment_save.xml
> +            android:id="@+id/cl_save_url_toast"
> cl_paste_clip_board 로 바꿔달라고 하면 화낼거야 자기얌?❤

내가 달링한테 화를 어떻게 내~💜

2022-03-06 11:11 UTC, ny2060 commented on app/src/main/java/org/sopt/havit/ui/save/SaveFragment.kt
> +                    this.getItemAt(0).text.toString().trim() // 클립보드에 저장된 첫번째 데이터
아마 제일 최근 복사한 데이터 같아요~~ 찾아봐도 첫번째 데이터라고만 나오네요 🤣

2022-03-06 12:24 UTC, KxxHyoRim approved these changes

2022-03-06 12:50 UTC, merged